"""Russian card names: gamer slang + compact labels for UI."""

# Привычные игровые названия (как в чатах/стримах)
CARD_NAMES_RU: dict[str, str] = {
    "Knight": "Рыцарь",
    "Archers": "Лучницы",
    "Goblins": "Гоблины",
    "Giant": "Гигант",
    "P.E.K.K.A": "ПЕККА",
    "Minions": "Миньоны",
    "Balloon": "Шар",
    "Witch": "Ведьма",
    "Barbarians": "Варвары",
    "Golem": "Голем",
    "Skeletons": "Скелеты",
    "Valkyrie": "Валькирия",
    "Skeleton Army": "Армия скелетов",
    "Bomber": "Бомбер",
    "Musketeer": "Мушкетёр",
    "Baby Dragon": "Дракончик",
    "Prince": "Принц",
    "Wizard": "Маг",
    "Mini P.E.K.K.A": "Мини-пекка",
    "Spear Goblins": "Копейщики",
    "Giant Skeleton": "ГигСкелет",
    "Hog Rider": "Хог",
    "Minion Horde": "Орда",
    "Ice Wizard": "Айс-Маг",
    "Royal Giant": "КорГиг",
    "Guards": "Стражи",
    "Princess": "Принцесса",
    "Dark Prince": "Тёмный принц",
    "Three Musketeers": "Три мушкета",
    "Lava Hound": "Лава",
    "Ice Spirit": "Ледяной дух",
    "Fire Spirit": "Огненный дух",
    "Miner": "Шахтёр",
    "Sparky": "Спарки",
    "Bowler": "Боулер",
    "Lumberjack": "Дровосек",
    "Battle Ram": "Таран",
    "Inferno Dragon": "Инферно-дракон",
    "Ice Golem": "Терпила",
    "Mega Minion": "МегаМуха",
    "Dart Goblin": "Плевака",
    "Goblin Gang": "Банда гоблинов",
    "Electro Wizard": "ЭлктроМаг",
    "Elite Barbarians": "Элитки",
    "Hunter": "Охотник",
    "Executioner": "Палач",
    "Bandit": "Бандитка",
    "Royal Recruits": "Рекруты",
    "Night Witch": "Ночная Ведьма",
    "Bats": "Мыши",
    "Royal Ghost": "Призрак",
    "Ram Rider": "Рем-Райдер",
    "Zappies": "Генераторы",
    "Rascals": "Разбойники",
    "Cannon Cart": "Повозка",
    "Mega Knight": "МегаНайт",
    "Skeleton Barrel": "Скелет-Бочка",
    "Flying Machine": "Летучка",
    "Wall Breakers": "Стенобои",
    "Royal Hogs": "Кабаны",
    "Goblin Giant": "Гоблин-Гигант",
    "Fisherman": "Рыбак",
    "Magic Archer": "Лучник",
    "Electro Dragon": "Электродракон",
    "Firecracker": "Ракетчица",
    "Mighty Miner": "Шахтёр",
    "Elixir Golem": "Элик-Голем",
    "Battle Healer": "Целительница",
    "Skeleton King": "Скелет-Король",
    "Archer Queen": "Королева",
    "Golden Knight": "Золотой рыцарь",
    "Monk": "Монах",
    "Skeleton Dragons": "Скелет-драконы",
    "Mother Witch": "Бабуля",
    "Electro Spirit": "Электродух",
    "Electro Giant": "ЭлектроГиг",
    "Phoenix": "Феникс",
    "Little Prince": "Малый принц",
    "Zap": "Зап",
    "Arrows": "Стрелы",
    "Fireball": "Фаербол",
    "Rocket": "Ракета",
    "Goblin Barrel": "Гоб-Бочка",
    "Freeze": "Фриз",
    "Mirror": "Зеркало",
    "Lightning": "Молния",
    "Poison": "Яд",
    "Graveyard": "Кладбище",
    "The Log": "Бревно",
    "Tornado": "Торнадо",
    "Clone": "Клон",
    "Earthquake": "Землетряс",
    "Barbarian Barrel": "Бочка",
    "Heal Spirit": "ХилДух",
    "Giant Snowball": "Снежок",
    "Royal Delivery": "Почта",
    "Cannon": "Пушка",
    "Goblin Hut": "Хижина",
    "Mortar": "Мортира",
    "Inferno Tower": "Инферно",
    "Bomb Tower": "Бомб-башня",
    "Barbarian Hut": "Хижина варваров",
    "Tesla": "Тесла",
    "Elixir Collector": "Сборщик",
    "X-Bow": "Арбалет",
    "Tombstone": "Надгробие",
    "Furnace": "Печь",
    "Goblin Cage": "Клетка",
    "Goblin Drill": "Бур",
    "Goblin Demolisher": "Подрывник",
    "Goblin Machine": "Гоб-Машина",
    "Goblinstein": "Гоблинштейн",
    "Goblin Curse": "Проклятие",
    "Berserker": "Берсерк",
    "Boss Bandit": "Гл-Бандитка",
    "Rune Giant": "РунГиг",
    "Spirit Empress": "Императрица",
    "Suspicious Bush": "Куст",
    "Vines": "Лоза",
    "Void": "Бездна",
    "Rage": "Ярость",
}

# Короткие подписи под картинкой (чтобы не налезали)
CARD_NAMES_SHORT: dict[str, str] = {
    "Goblin Gang": "Банда",
    "Goblin Barrel": "Гоб-Бочка",
    "Ice Spirit": "Айс-Дух",
    "Inferno Tower": "Инферно",
    "Hog Rider": "Хог",
    "Royal Giant": "КорГиг",
    "Three Musketeers": "Мушкетки",
    "Elite Barbarians": "Элитки",
    "Skeleton Army": "Армия",
    "Giant Skeleton": "ГигСкелет",
    "Electro Wizard": "Эл-Маг",
    "Ice Wizard": "Айс-Маг",
    "Mini P.E.K.K.A": "Мини-Пекка",
    "P.E.K.K.A": "ПЕККА",
    "Royal Recruits": "Рекруты",
    "Wall Breakers": "Стенобои",
    "Skeleton Barrel": "Скел-Бочка",
    "Flying Machine": "Летучка",
    "Goblin Giant": "ГоблинГиг",
    "Electro Dragon": "Эл-Дракон",
    "Inferno Dragon": "Инф-Дракон",
    "Skeleton Dragons": "Скел-Драконы",
    "Elixir Golem": "Эликсирный",
    "Electro Giant": "Эл-Гигант",
    "Battle Healer": "Целительница",
    "Skeleton King": "Скел-Король",
    "Golden Knight": "Зол-рыцарь",
    "Mother Witch": "Бабуля",
    "Barbarian Barrel": "Бочка",
    "Barbarian Hut": "Хиж-Варв",
    "Goblin Hut": "Хижина",
    "Elixir Collector": "Сборщик",
    "Royal Delivery": "Почта",
    "Giant Snowball": "Снежок",
    "Heal Spirit": "Хил-дух",
    "Electro Spirit": "Эл-дух",
    "Fire Spirit": "Огн-дух",
    "Spear Goblins": "Копейщики",
    "Minion Horde": "Орда",
    "Mega Knight": "МегаНайт",
    "Mega Minion": "МегаМуха",
    "Magic Archer": "Маг-Лучник",
    "Dark Prince": "Тём-принц",
    "Night Witch": "Ночь-Ведьма",
    "Lava Hound": "Лава",
    "Ram Rider": "Рем",
    "Battle Ram": "Таран",
    "Cannon Cart": "Повозка",
    "Royal Hogs": "Кабаны",
    "Royal Ghost": "Призрак",
    "Archer Queen": "Королева",
    "Mighty Miner": "Шахтёр",
    "Little Prince": "Мал-Принц",
    "Baby Dragon": "Дракончик",
    "Goblin Demolisher": "Подрывник",
    "Goblin Machine": "Гоб-Машина",
    "Goblinstein": "Гоблинштейн",
    "Goblin Curse": "Проклятие",
    "Berserker": "Берсерк",
    "Boss Bandit": "Гл-Бандитка",
    "Rune Giant": "РунГиг",
    "Spirit Empress": "Императрица",
    "Suspicious Bush": "Куст",
    "Vines": "Лоза",
    "Void": "Бездна",
    "Rage": "Ярость",
}


def card_name_ru(name: str, *, short: bool = False) -> str:
    if short:
        return CARD_NAMES_SHORT.get(name) or CARD_NAMES_RU.get(name, name)
    return CARD_NAMES_RU.get(name, name)
