"""Russian display names for Clash Royale cards (in-game localization)."""

CARD_NAMES_RU: dict[str, str] = {
    "Knight": "Рыцарь",
    "Archers": "Лучницы",
    "Goblins": "Гоблины",
    "Giant": "Гигант",
    "P.E.K.K.A": "П.Е.К.К.А",
    "Minions": "Миньоны",
    "Balloon": "Шар",
    "Witch": "Колдунья",
    "Barbarians": "Варвары",
    "Golem": "Голем",
    "Skeletons": "Скелеты",
    "Valkyrie": "Valkyria",
    "Skeleton Army": "Армия скелетов",
    "Bomber": "Подрывник",
    "Musketeer": "Мушкетёр",
    "Baby Dragon": "Дракончик",
    "Prince": "Принц",
    "Wizard": "Маг",
    "Mini P.E.K.K.A": "Мини П.Е.К.К.А",
    "Spear Goblins": "Гоблины-копейщики",
    "Giant Skeleton": "Гигантский скелет",
    "Hog Rider": "Наездник на кабане",
    "Minion Horde": "Орда миньонов",
    "Ice Wizard": "Ледяной маг",
    "Royal Giant": "Королевский гигант",
    "Guards": "Стражи",
    "Princess": "Принцесса",
    "Dark Prince": "Тёмный принц",
    "Three Musketeers": "Три мушкетёра",
    "Lava Hound": "Лавовая гончая",
    "Ice Spirit": "Ледяной дух",
    "Fire Spirit": "Огненный дух",
    "Miner": "Шахтёр",
    "Sparky": "Искра",
    "Bowler": "Метатель",
    "Lumberjack": "Дровосек",
    "Battle Ram": "Боевой баран",
    "Inferno Dragon": "Инферно-дракон",
    "Ice Golem": "Ледяной голем",
    "Mega Minion": "Мегаминьон",
    "Dart Goblin": "Гоблин-стрелок",
    "Goblin Gang": "Гоблинская банда",
    "Electro Wizard": "Электромаг",
    "Elite Barbarians": "Элитные варвары",
    "Hunter": "Охотник",
    "Executioner": "Палач",
    "Bandit": "Бандитка",
    "Royal Recruits": "Королевские рекруты",
    "Night Witch": "Ночная колдунья",
    "Bats": "Летучие мыши",
    "Royal Ghost": "Королевский призрак",
    "Ram Rider": "Наездник на баране",
    "Zappies": "Разряды",
    "Rascals": "Хулиганы",
    "Cannon Cart": "Пушечная телега",
    "Mega Knight": "Мегарыцарь",
    "Skeleton Barrel": "Скелет-бочка",
    "Flying Machine": "Летающая машина",
    "Wall Breakers": "Стеноломы",
    "Royal Hogs": "Королевские кабаны",
    "Goblin Giant": "Гоблин-гигант",
    "Fisherman": "Рыбак",
    "Magic Archer": "Маг-лучник",
    "Electro Dragon": "Электродракон",
    "Firecracker": "Хлопушка",
    "Mighty Miner": "Могучий шахтёр",
    "Elixir Golem": "Эликсирный голем",
    "Battle Healer": "Боевой лекарь",
    "Skeleton King": "Король скелетов",
    "Archer Queen": "Королева лучниц",
    "Golden Knight": "Золотой рыцарь",
    "Monk": "Монах",
    "Skeleton Dragons": "Скелет-драконы",
    "Mother Witch": "Матка-колдунья",
    "Electro Spirit": "Электродух",
    "Electro Giant": "Электроголем",
    "Phoenix": "Феникс",
    "Little Prince": "Маленький принц",
    "Zap": "Разряд",
    "Arrows": "Стрелы",
    "Fireball": "Огненный шар",
    "Rocket": "Ракета",
    "Goblin Barrel": "Бочка гоблинов",
    "Freeze": "Заморозка",
    "Mirror": "Зеркало",
    "Lightning": "Молния",
    "Poison": "Яд",
    "Graveyard": "Кладбище",
    "The Log": "Бревно",
    "Tornado": "Торнадо",
    "Clone": "Клон",
    "Earthquake": "Землетрясение",
    "Barbarian Barrel": "Бочка варваров",
    "Heal Spirit": "Дух исцеления",
    "Giant Snowball": "Снежок",
    "Royal Delivery": "Королевская доставка",
    "Cannon": "Пушка",
    "Goblin Hut": "Хижина гоблинов",
    "Mortar": "Миномёт",
    "Inferno Tower": "Инферно-башня",
    "Bomb Tower": "Башня с бомбами",
    "Barbarian Hut": "Хижина варваров",
    "Tesla": "Тесла",
    "Elixir Collector": "Сборщик эликсира",
    "X-Bow": "Арбалет",
    "Tombstone": "Надгробие",
    "Furnace": "Печь",
    "Goblin Cage": "Клетка гоблинов",
    "Goblin Drill": "Бур гоблинов",
}


def card_name_ru(name: str) -> str:
    return CARD_NAMES_RU.get(name, name)
