"""Данные о картах: тип, эликсир, счётчики и синергии."""

CARD_META: dict[str, dict] = {
    "Knight": {"elixir": 3, "type": "troop", "role": "tank"},
    "Archers": {"elixir": 3, "type": "troop", "role": "support"},
    "Goblins": {"elixir": 2, "type": "troop", "role": "swarm"},
    "Giant": {"elixir": 5, "type": "troop", "role": "win_condition"},
    "P.E.K.K.A": {"elixir": 7, "type": "troop", "role": "win_condition"},
    "Minions": {"elixir": 3, "type": "troop", "role": "air"},
    "Balloon": {"elixir": 5, "type": "troop", "role": "win_condition"},
    "Witch": {"elixir": 5, "type": "troop", "role": "support"},
    "Barbarians": {"elixir": 5, "type": "troop", "role": "swarm"},
    "Golem": {"elixir": 8, "type": "troop", "role": "win_condition"},
    "Skeletons": {"elixir": 1, "type": "troop", "role": "cycle"},
    "Valkyrie": {"elixir": 4, "type": "troop", "role": "tank"},
    "Skeleton Army": {"elixir": 3, "type": "troop", "role": "swarm"},
    "Bomber": {"elixir": 2, "type": "troop", "role": "splash"},
    "Musketeer": {"elixir": 4, "type": "troop", "role": "support"},
    "Baby Dragon": {"elixir": 4, "type": "troop", "role": "splash"},
    "Prince": {"elixir": 5, "type": "troop", "role": "win_condition"},
    "Wizard": {"elixir": 5, "type": "troop", "role": "splash"},
    "Mini P.E.K.K.A": {"elixir": 4, "type": "troop", "role": "tank"},
    "Spear Goblins": {"elixir": 2, "type": "troop", "role": "swarm"},
    "Giant Skeleton": {"elixir": 6, "type": "troop", "role": "tank"},
    "Hog Rider": {"elixir": 4, "type": "troop", "role": "win_condition"},
    "Minion Horde": {"elixir": 5, "type": "troop", "role": "swarm"},
    "Ice Wizard": {"elixir": 3, "type": "troop", "role": "support"},
    "Royal Giant": {"elixir": 6, "type": "troop", "role": "win_condition"},
    "Guards": {"elixir": 3, "type": "troop", "role": "tank"},
    "Princess": {"elixir": 3, "type": "troop", "role": "support"},
    "Dark Prince": {"elixir": 4, "type": "troop", "role": "tank"},
    "Three Musketeers": {"elixir": 9, "type": "troop", "role": "win_condition"},
    "Lava Hound": {"elixir": 7, "type": "troop", "role": "win_condition"},
    "Ice Spirit": {"elixir": 1, "type": "troop", "role": "cycle"},
    "Fire Spirit": {"elixir": 1, "type": "troop", "role": "cycle"},
    "Miner": {"elixir": 3, "type": "troop", "role": "win_condition"},
    "Sparky": {"elixir": 6, "type": "troop", "role": "win_condition"},
    "Bowler": {"elixir": 5, "type": "troop", "role": "splash"},
    "Lumberjack": {"elixir": 4, "type": "troop", "role": "support"},
    "Battle Ram": {"elixir": 4, "type": "troop", "role": "win_condition"},
    "Inferno Dragon": {"elixir": 4, "type": "troop", "role": "support"},
    "Ice Golem": {"elixir": 2, "type": "troop", "role": "tank"},
    "Mega Minion": {"elixir": 3, "type": "troop", "role": "air"},
    "Dart Goblin": {"elixir": 3, "type": "troop", "role": "support"},
    "Goblin Gang": {"elixir": 3, "type": "troop", "role": "swarm"},
    "Electro Wizard": {"elixir": 4, "type": "troop", "role": "support"},
    "Elite Barbarians": {"elixir": 6, "type": "troop", "role": "win_condition"},
    "Hunter": {"elixir": 4, "type": "troop", "role": "support"},
    "Executioner": {"elixir": 5, "type": "troop", "role": "splash"},
    "Bandit": {"elixir": 3, "type": "troop", "role": "win_condition"},
    "Royal Recruits": {"elixir": 7, "type": "troop", "role": "swarm"},
    "Night Witch": {"elixir": 4, "type": "troop", "role": "support"},
    "Bats": {"elixir": 2, "type": "troop", "role": "swarm"},
    "Royal Ghost": {"elixir": 3, "type": "troop", "role": "win_condition"},
    "Ram Rider": {"elixir": 5, "type": "troop", "role": "win_condition"},
    "Zappies": {"elixir": 4, "type": "troop", "role": "support"},
    "Rascals": {"elixir": 5, "type": "troop", "role": "support"},
    "Cannon Cart": {"elixir": 5, "type": "troop", "role": "support"},
    "Mega Knight": {"elixir": 7, "type": "troop", "role": "tank"},
    "Skeleton Barrel": {"elixir": 3, "type": "troop", "role": "win_condition"},
    "Flying Machine": {"elixir": 4, "type": "troop", "role": "air"},
    "Wall Breakers": {"elixir": 2, "type": "troop", "role": "win_condition"},
    "Royal Hogs": {"elixir": 5, "type": "troop", "role": "win_condition"},
    "Goblin Giant": {"elixir": 6, "type": "troop", "role": "win_condition"},
    "Fisherman": {"elixir": 3, "type": "troop", "role": "support"},
    "Magic Archer": {"elixir": 4, "type": "troop", "role": "support"},
    "Electro Dragon": {"elixir": 5, "type": "troop", "role": "splash"},
    "Firecracker": {"elixir": 3, "type": "troop", "role": "support"},
    "Mighty Miner": {"elixir": 4, "type": "troop", "role": "win_condition"},
    "Elixir Golem": {"elixir": 3, "type": "troop", "role": "win_condition"},
    "Battle Healer": {"elixir": 4, "type": "troop", "role": "support"},
    "Skeleton King": {"elixir": 4, "type": "troop", "role": "win_condition"},
    "Archer Queen": {"elixir": 5, "type": "troop", "role": "win_condition"},
    "Golden Knight": {"elixir": 4, "type": "troop", "role": "win_condition"},
    "Monk": {"elixir": 5, "type": "troop", "role": "support"},
    "Skeleton Dragons": {"elixir": 4, "type": "troop", "role": "air"},
    "Mother Witch": {"elixir": 4, "type": "troop", "role": "support"},
    "Electro Spirit": {"elixir": 1, "type": "troop", "role": "cycle"},
    "Electro Giant": {"elixir": 7, "type": "troop", "role": "win_condition"},
    "Phoenix": {"elixir": 4, "type": "troop", "role": "support"},
    "Little Prince": {"elixir": 3, "type": "troop", "role": "support"},
    "Zap": {"elixir": 2, "type": "spell", "role": "spell"},
    "Arrows": {"elixir": 3, "type": "spell", "role": "spell"},
    "Fireball": {"elixir": 4, "type": "spell", "role": "spell"},
    "Rocket": {"elixir": 6, "type": "spell", "role": "spell"},
    "Goblin Barrel": {"elixir": 3, "type": "spell", "role": "win_condition"},
    "Freeze": {"elixir": 4, "type": "spell", "role": "spell"},
    "Mirror": {"elixir": 1, "type": "spell", "role": "spell"},
    "Lightning": {"elixir": 6, "type": "spell", "role": "spell"},
    "Poison": {"elixir": 4, "type": "spell", "role": "spell"},
    "Graveyard": {"elixir": 5, "type": "spell", "role": "win_condition"},
    "The Log": {"elixir": 2, "type": "spell", "role": "spell"},
    "Tornado": {"elixir": 3, "type": "spell", "role": "spell"},
    "Clone": {"elixir": 3, "type": "spell", "role": "spell"},
    "Earthquake": {"elixir": 3, "type": "spell", "role": "spell"},
    "Barbarian Barrel": {"elixir": 2, "type": "spell", "role": "spell"},
    "Heal Spirit": {"elixir": 1, "type": "spell", "role": "cycle"},
    "Giant Snowball": {"elixir": 2, "type": "spell", "role": "spell"},
    "Royal Delivery": {"elixir": 3, "type": "spell", "role": "spell"},
    "Cannon": {"elixir": 3, "type": "building", "role": "building"},
    "Goblin Hut": {"elixir": 5, "type": "building", "role": "building"},
    "Mortar": {"elixir": 4, "type": "building", "role": "win_condition"},
    "Inferno Tower": {"elixir": 5, "type": "building", "role": "building"},
    "Bomb Tower": {"elixir": 4, "type": "building", "role": "building"},
    "Barbarian Hut": {"elixir": 7, "type": "building", "role": "building"},
    "Tesla": {"elixir": 4, "type": "building", "role": "building"},
    "Elixir Collector": {"elixir": 6, "type": "building", "role": "building"},
    "X-Bow": {"elixir": 6, "type": "building", "role": "win_condition"},
    "Tombstone": {"elixir": 3, "type": "building", "role": "building"},
    "Furnace": {"elixir": 4, "type": "building", "role": "building"},
    "Goblin Cage": {"elixir": 4, "type": "building", "role": "building"},
    "Goblin Drill": {"elixir": 4, "type": "building", "role": "win_condition"},
}

COUNTERS: dict[str, list[str]] = {
    "Hog Rider": ["Cannon", "Tesla", "Tornado", "Ice Golem", "Skeleton Army"],
    "Balloon": ["Inferno Tower", "Musketeer", "Wizard", "Mega Minion", "Inferno Dragon"],
    "Golem": ["Inferno Tower", "Inferno Dragon", "P.E.K.K.A", "Mini P.E.K.K.A"],
    "Graveyard": ["Poison", "Valkyrie", "Wizard", "Baby Dragon", "Bowler"],
    "X-Bow": ["Royal Giant", "Giant", "Earthquake", "Rocket", "Miner"],
    "Mortar": ["Royal Giant", "Giant", "Earthquake", "Miner", "Hog Rider"],
    "Royal Giant": ["Inferno Tower", "P.E.K.K.A", "Mini P.E.K.K.A", "Inferno Dragon"],
    "Goblin Barrel": ["The Log", "Arrows", "Barbarian Barrel", "Giant Snowball", "Princess"],
    "Lava Hound": ["Inferno Tower", "Inferno Dragon", "Mega Minion", "Musketeer"],
    "Miner": ["Knight", "Valkyrie", "Skeleton Army", "Guards", "Cannon"],
    "Mega Knight": ["Inferno Tower", "P.E.K.K.A", "Mini P.E.K.K.A", "Inferno Dragon", "Knight"],
    "Electro Giant": ["Inferno Tower", "Inferno Dragon", "P.E.K.K.A", "Mini P.E.K.K.A"],
    "Wall Breakers": ["The Log", "Barbarian Barrel", "Skeleton Army", "Goblin Gang"],
    "Battle Ram": ["Cannon", "Tesla", "Tornado", "Skeleton Army"],
    "Skeleton Barrel": ["Arrows", "Zap", "The Log", "Princess", "Musketeer"],
    "Elite Barbarians": ["Skeleton Army", "Valkyrie", "Mini P.E.K.K.A", "Knight"],
    "Three Musketeers": ["Fireball", "Lightning", "Rocket", "Valkyrie"],
    "Sparky": ["Zap", "Rocket", "Lightning", "Goblin Barrel", "Miner"],
    "Giant": ["Inferno Tower", "Inferno Dragon", "Mini P.E.K.K.A", "P.E.K.K.A"],
    "P.E.K.K.A": ["Skeleton Army", "Guards", "Goblin Gang", "Inferno Tower"],
}

SYNERGIES: dict[str, list[str]] = {
    "Hog Rider": ["Ice Golem", "Ice Spirit", "Skeletons", "Musketeer", "Cannon", "Fireball"],
    "Balloon": ["Lumberjack", "Freeze", "Baby Dragon", "Tornado", "Miner"],
    "Golem": ["Night Witch", "Baby Dragon", "Lightning", "Tornado", "Elixir Collector"],
    "Graveyard": ["Freeze", "Poison", "Knight", "Ice Wizard", "Baby Dragon"],
    "Lava Hound": ["Balloon", "Mega Minion", "Tombstone", "Lightning", "Arrows"],
    "X-Bow": ["Tesla", "Archers", "Knight", "Ice Spirit", "Skeletons"],
    "Mortar": ["Knight", "Archers", "Skeletons", "Ice Spirit", "Rocket"],
    "Royal Giant": ["Fisherman", "Hunter", "Lightning", "Fireball", "Electro Spirit"],
    "Goblin Barrel": ["Princess", "Goblin Gang", "Knight", "Inferno Tower", "Rocket"],
    "Miner": ["Poison", "Wall Breakers", "Bats", "Skeleton Army", "Goblin Gang"],
    "Mega Knight": ["Inferno Dragon", "Bats", "Zap", "Miner", "Poison"],
    "Electro Giant": ["Tornado", "Lightning", "Golden Knight", "Battle Healer"],
    "Hunter": ["Royal Giant", "Giant", "Elixir Golem", "Freeze"],
    "Giant": ["Musketeer", "Wizard", "Mini P.E.K.K.A", "Arrows", "Zap"],
    "P.E.K.K.A": ["Battle Ram", "Poison", "Electro Wizard", "Zap", "Bandit"],
    "Wall Breakers": ["Miner", "Goblin Gang", "Fire Spirit", "Bats", "Skeleton Army"],
    "Battle Ram": ["Bandit", "Dark Prince", "Royal Ghost", "Zap", "Fireball"],
    "Skeleton King": ["Graveyard", "Giant Skeleton", "Tornado", "Arrows"],
    "Archer Queen": ["P.E.K.K.A", "Giant", "Royal Giant", "Skeleton Army"],
}

ARENA_CARD_POOL: dict[str, list[str]] = {
    "low": ["Knight", "Archers", "Goblins", "Giant", "Minions", "Arrows", "Fireball",
            "Zap", "Cannon", "Skeletons", "Musketeer", "Mini P.E.K.K.A", "Hog Rider",
            "Valkyrie", "Bomber", "Barbarians", "Ice Spirit", "Fire Spirit"],
    "mid": ["Balloon", "Witch", "Prince", "Wizard", "Goblin Barrel", "Inferno Tower",
            "Baby Dragon", "Skeleton Army", "Tesla", "Mortar", "Tornado", "The Log",
            "Ice Golem", "Mega Minion", "Dart Goblin", "Goblin Gang", "Battle Ram"],
    "high": ["Lava Hound", "Graveyard", "Sparky", "Miner", "Bandit", "Night Witch",
             "Royal Ghost", "Magic Archer", "Electro Wizard", "Mega Knight",
             "Wall Breakers", "Elixir Golem", "Skeleton King", "Phoenix"],
}

WIN_CONDITIONS = {
    "Hog Rider", "Balloon", "Golem", "Graveyard", "X-Bow", "Mortar", "Royal Giant",
    "Goblin Barrel", "Lava Hound", "Miner", "Giant", "P.E.K.K.A", "Battle Ram",
    "Wall Breakers", "Royal Hogs", "Goblin Giant", "Elixir Giant", "Electro Giant",
    "Skeleton Barrel", "Sparky", "Three Musketeers", "Elite Barbarians", "Goblin Drill",
}


def get_card_elixir(name: str) -> int:
    return CARD_META.get(name, {}).get("elixir", 4)


def get_card_role(name: str) -> str:
    return CARD_META.get(name, {}).get("role", "support")
