"""Russian card names: gamer slang + compact labels for UI."""

# Привычные игровые названия (как в чатах/стримах)
CARD_NAMES_RU: dict[str, str] = {
    "Knight": "Рыцарь",
    "Archers": "Лучницы",
    "Goblins": "Гоблины",
    "Giant": "Гигант",
    "P.E.K.K.A": "Пекка",
    "Minions": "Миньоны",
    "Balloon": "Шар",
    "Witch": "Колдунья",
    "Barbarians": "Варвары",
    "Golem": "Голем",
    "Skeletons": "Скелеты",
    "Valkyrie": "Вalk",
    "Skeleton Army": "Армия скелетов",
    "Bomber": "Подрывник",
    "Musketeer": "Мушкетёр",
    "Baby Dragon": "Дракончик",
    "Prince": "Принц",
    "Wizard": "Маг",
    "Mini P.E.K.K.A": "Мини-пекка",
    "Spear Goblins": "Копейщики",
    "Giant Skeleton": "Гигант-скелет",
    "Hog Rider": "Хог",
    "Minion Horde": "Орда",
    "Ice Wizard": "Айс-маг",
    "Royal Giant": "RG",
    "Guards": "Стражи",
    "Princess": "Принцесса",
    "Dark Prince": "Тёмный принц",
    "Three Musketeers": "Три мушкета",
    "Lava Hound": "Лава",
    "Ice Spirit": "Айс-дух",
    "Fire Spirit": "Огненный дух",
    "Miner": "Шахтёр",
    "Sparky": "Искра",
    "Bowler": "Метатель",
    "Lumberjack": "Дровосек",
    "Battle Ram": "Баран",
    "Inferno Dragon": "Инферно-дракон",
    "Ice Golem": "Айс-голем",
    "Mega Minion": "Мегаминьон",
    "Dart Goblin": "Дарт",
    "Goblin Gang": "Банда гоблинов",
    "Electro Wizard": "Э-маг",
    "Elite Barbarians": "Элитки",
    "Hunter": "Охотник",
    "Executioner": "Палач",
    "Bandit": "Бандитка",
    "Royal Recruits": "Рекруты",
    "Night Witch": "Ночная колдунья",
    "Bats": "Летучки",
    "Royal Ghost": "Призрак",
    "Ram Rider": "Рам-райдер",
    "Zappies": "Разряды",
    "Rascals": "Хулиганы",
    "Cannon Cart": "Пушка-кат",
    "Mega Knight": "Мега-рыцарь",
    "Skeleton Barrel": "Скелет-бочка",
    "Flying Machine": "Летающая машина",
    "Wall Breakers": "Стеноломы",
    "Royal Hogs": "Кабаны",
    "Goblin Giant": "Гоблин-гигант",
    "Fisherman": "Рыбак",
    "Magic Archer": "Маг-лучник",
    "Electro Dragon": "Электродракон",
    "Firecracker": "Хлопушка",
    "Mighty Miner": "Шахтёр",
    "Elixir Golem": "Эликсирный голем",
    "Battle Healer": "Лекарь",
    "Skeleton King": "Скелет-король",
    "Archer Queen": "Куин",
    "Golden Knight": "Золотой рыцарь",
    "Monk": "Монах",
    "Skeleton Dragons": "Скелет-драконы",
    "Mother Witch": "Матка",
    "Electro Spirit": "Электродух",
    "Electro Giant": "Электроголем",
    "Phoenix": "Феникс",
    "Little Prince": "Малый принц",
    "Zap": "Зап",
    "Arrows": "Стрелы",
    "Fireball": "Фаербол",
    "Rocket": "Ракета",
    "Goblin Barrel": "Бочка",
    "Freeze": "Фриз",
    "Mirror": "Зеркало",
    "Lightning": "Молния",
    "Poison": "Яд",
    "Graveyard": "Кладбище",
    "The Log": "Лог",
    "Tornado": "Торнадо",
    "Clone": "Клон",
    "Earthquake": "Землетрясение",
    "Barbarian Barrel": "Бочка варваров",
    "Heal Spirit": "Хил-дух",
    "Giant Snowball": "Снежок",
    "Royal Delivery": "Доставка",
    "Cannon": "Пушка",
    "Goblin Hut": "Хижина",
    "Mortar": "Миномёт",
    "Inferno Tower": "Инферно",
    "Bomb Tower": "Бомб-башня",
    "Barbarian Hut": "Хижина варваров",
    "Tesla": "Тесла",
    "Elixir Collector": "Сборщик",
    "X-Bow": "Арбалет",
    "Tombstone": "Надгробие",
    "Furnace": "Печь",
    "Goblin Cage": "Клетка",
    "Goblin Drill": "Бур",
}

# Короткие подписи под картинкой (чтобы не налезали)
CARD_NAMES_SHORT: dict[str, str] = {
    "Goblin Gang": "Банда",
    "Goblin Barrel": "Бочка",
    "Ice Spirit": "Айс",
    "Inferno Tower": "Инферно",
    "Hog Rider": "Хог",
    "Royal Giant": "RG",
    "Three Musketeers": "3M",
    "Elite Barbarians": "Элитки",
    "Skeleton Army": "Армия",
    "Giant Skeleton": "Гиг-скелет",
    "Electro Wizard": "Э-маг",
    "Ice Wizard": "Айс-маг",
    "Mini P.E.K.K.A": "Мини-П",
    "P.E.K.K.A": "Пекка",
    "Royal Recruits": "Рекруты",
    "Wall Breakers": "Стеноломы",
    "Skeleton Barrel": "Скел-бочка",
    "Flying Machine": "Лет-машина",
    "Goblin Giant": "Гоб-гигант",
    "Electro Dragon": "Э-дракон",
    "Inferno Dragon": "И-дракон",
    "Skeleton Dragons": "Скел-драконы",
    "Elixir Golem": "Элик-голем",
    "Electro Giant": "Э-голем",
    "Battle Healer": "Лекарь",
    "Skeleton King": "Скел-король",
    "Golden Knight": "Зол. рыцарь",
    "Mother Witch": "Матка",
    "Barbarian Barrel": "Бочка варв",
    "Barbarian Hut": "Хиж. варв",
    "Goblin Hut": "Хижина",
    "Elixir Collector": "Сборщик",
    "Royal Delivery": "Доставка",
    "Giant Snowball": "Снежок",
    "Heal Spirit": "Хил",
    "Electro Spirit": "Э-дух",
    "Fire Spirit": "Огн. дух",
    "Spear Goblins": "Копейщ.",
    "Minion Horde": "Орда",
    "Mega Knight": "МК",
    "Mega Minion": "Мегаминьон",
    "Magic Archer": "Маг-лучник",
    "Dark Prince": "Т. принц",
    "Night Witch": "Н. колдунья",
    "Lava Hound": "Лава",
    "Ram Rider": "Рам",
    "Battle Ram": "Баран",
    "Cannon Cart": "Пуш-кат",
    "Royal Hogs": "Кабаны",
    "Royal Ghost": "Призрак",
    "Archer Queen": "Куин",
    "Mighty Miner": "Шахтёр",
    "Little Prince": "М. принц",
    "Baby Dragon": "Дракончик",
}


def card_name_ru(name: str, *, short: bool = False) -> str:
    if short:
        return CARD_NAMES_SHORT.get(name) or CARD_NAMES_RU.get(name, name)
    return CARD_NAMES_RU.get(name, name)
