"""Meme / rofl deck presets — post-ironic chaos in Russian."""

from __future__ import annotations

import random
from dataclasses import dataclass


@dataclass(frozen=True)
class RoflDeck:
    key: str
    name: str
    cards: tuple[str, ...]
    tagline: str


ROFL_DECKS: list[RoflDeck] = [
    RoflDeck(
        "skill-issue",
        "Нет скилла",
        (
            "Hog Rider",
            "Balloon",
            "Royal Giant",
            "Elite Barbarians",
            "Mega Knight",
            "Sparky",
            "X-Bow",
            "P.E.K.K.A",
        ),
        "Просто играй лучше. Колода специально против этого.",
    ),
    RoflDeck(
        "npc-pack",
        "Набор NPC",
        (
            "Knight",
            "Archers",
            "Minions",
            "Arrows",
            "Fireball",
            "Giant",
            "Witch",
            "Baby Dragon",
        ),
        "Игрок с настройками по умолчанию. Без DLC на мозги.",
    ),
    RoflDeck(
        "delulu",
        "Делулу-пуш",
        (
            "Balloon",
            "Rage",
            "Clone",
            "Freeze",
            "Wizard",
            "Witch",
            "Sparky",
            "Mirror",
        ),
        "Сейчас точно затащу. Король всё равно упадёт — нет.",
    ),
    RoflDeck(
        "sigma-3am",
        "Сигма в 3 ночи",
        (
            "P.E.K.K.A",
            "Mega Knight",
            "Electro Giant",
            "Golem",
            "Giant",
            "Prince",
            "Dark Prince",
            "Lumberjack",
        ),
        "Проснулся. Заапгрейдил. Проиграл. Повтори.",
    ),
    RoflDeck(
        "ohio-boss",
        "Босс из Огайо",
        (
            "Mega Knight",
            "Electro Giant",
            "P.E.K.K.A",
            "Sparky",
            "Royal Giant",
            "Golem",
            "Lava Hound",
            "Wizard",
        ),
        "Только в Огайо. На деле — в каждом втором матче.",
    ),
    RoflDeck(
        "main-character",
        "Главный герой",
        (
            "Golden Knight",
            "Princess",
            "Prince",
            "Dark Prince",
            "Wizard",
            "Witch",
            "Sparky",
            "Mega Knight",
        ),
        "Броня сюжета не включилась. Финал — поражение.",
    ),
    RoflDeck(
        "low-taper",
        "Низкий пробор",
        (
            "Royal Ghost",
            "Bandit",
            "Miner",
            "Goblin Drill",
            "Dart Goblin",
            "Skeleton Barrel",
            "Wall Breakers",
            "The Log",
        ),
        "Какой пробор тебе нужен? Вот тебе колода на мосту.",
    ),
    RoflDeck(
        "trust-me-bro",
        "Поверь, братан",
        (
            "Elite Barbarians",
            "Rage",
            "Freeze",
            "Mirror",
            "Goblin Barrel",
            "Wall Breakers",
            "Skeleton Barrel",
            "Dart Goblin",
        ),
        "Это последний пуш, честно. Спойлер: не последний.",
    ),
    RoflDeck(
        "chat-real",
        "Чат, это реально?",
        (
            "Mirror",
            "Clone",
            "Rage",
            "Freeze",
            "Tornado",
            "Zap",
            "The Log",
            "Giant Snowball",
        ),
        "Чат, это можно выиграть? Нет. Спасибо за внимание.",
    ),
    RoflDeck(
        "tiktok-montage",
        "ТикТок-монтаж",
        (
            "Sparky",
            "Inferno Dragon",
            "Balloon",
            "Freeze",
            "Rage",
            "Mirror",
            "Clone",
            "Mega Minion",
        ),
        "Клип на полсекунды, минус восемь эликсира и полный угар.",
    ),
    RoflDeck(
        "mom-bedtime",
        "Ещё один матч",
        (
            "Golem",
            "Lava Hound",
            "P.E.K.K.A",
            "Sparky",
            "Three Musketeers",
            "Electro Giant",
            "Giant",
            "Freeze",
        ),
        "Мама сказала спать. Ты сказал «ещё один». Классика.",
    ),
    RoflDeck(
        "l-plus-ratio",
        "Лайк + рейд",
        (
            "Rocket",
            "Fireball",
            "Lightning",
            "Poison",
            "Earthquake",
            "Arrows",
            "Zap",
            "The Log",
        ),
        "Войск нет. Зато лайк на короля закинуть можно.",
    ),
    RoflDeck(
        "fanum-tax",
        "Налог на эликсир",
        (
            "Goblin Cage",
            "Elixir Collector",
            "Miner",
            "Goblin Drill",
            "Skeletons",
            "Ice Spirit",
            "Goblin Gang",
            "Fire Spirit",
        ),
        "Забираем эликсир. Отдаём кубки. Справедливо.",
    ),
    RoflDeck(
        "gym-bro",
        "Качок на мосту",
        (
            "Hog Rider",
            "Elite Barbarians",
            "Rage",
            "Prince",
            "P.E.K.K.A",
            "Giant",
            "Balloon",
            "Zap",
        ),
        "День ног — каждый раунд. Кардио — это поражение.",
    ),
    RoflDeck(
        "grandma-hangup",
        "Бабушка положила трубку",
        (
            "Graveyard",
            "Mirror",
            "Clone",
            "Tornado",
            "Freeze",
            "Poison",
            "Bowler",
            "Ice Wizard",
        ),
        "Объяснял колоду бабушке. Она повесила трубку через четыре карты.",
    ),
    RoflDeck(
        "ping-999",
        "Пинг 999",
        (
            "Golem",
            "Lava Hound",
            "Sparky",
            "Mega Knight",
            "Electro Giant",
            "P.E.K.K.A",
            "Giant",
            "Three Musketeers",
        ),
        "Лагает не интернет. Лагает решение играть это.",
    ),
    RoflDeck(
        "based-cringe",
        "База и кринж",
        (
            "Mirror",
            "Clone",
            "Rage",
            "Goblin Barrel",
            "Miner",
            "Wall Breakers",
            "Elite Barbarians",
            "Wizard",
        ),
        "Одновременно база и кринж. Колода Шрёдингера.",
    ),
    RoflDeck(
        "steal-brainrot",
        "Украл с ТикТока",
        (
            "Minion Horde",
            "Skeleton Army",
            "Goblin Gang",
            "Elite Barbarians",
            "Wizard",
            "Witch",
            "Fireball",
            "Rage",
        ),
        "Снял чужую колоду с ТикТока. Вернул только минус кубки.",
    ),
    RoflDeck(
        "rizz-minus",
        "Харизма −100",
        (
            "Prince",
            "Dark Prince",
            "Knight",
            "Guards",
            "Valkyrie",
            "Mini P.E.K.K.A",
            "Barbarians",
            "Arrows",
        ),
        "Харизмы нет. Кубки у соперника.",
    ),
    RoflDeck(
        "touch-grass",
        "Тронь траву (нет)",
        (
            "Cannon",
            "Tesla",
            "Inferno Tower",
            "Tombstone",
            "Goblin Hut",
            "Barbarian Hut",
            "Goblin Cage",
            "X-Bow",
        ),
        "Сказали выйти на улицу. Собрали только постройки у башни.",
    ),
    RoflDeck(
        "gen-alpha",
        "Сборная зумеров",
        (
            "Mega Knight",
            "Elite Barbarians",
            "Wizard",
            "Witch",
            "Sparky",
            "Freeze",
            "Rage",
            "Mirror",
        ),
        "Сборная, которая смеётся над твоим пушем в рейтинг.",
    ),
    RoflDeck(
        "aura-farm",
        "Фарм ауры",
        (
            "Golden Knight",
            "Princess",
            "Sparky",
            "Freeze",
            "Mirror",
            "Wizard",
            "Balloon",
            "The Log",
        ),
        "Фармишь ауру. Сливаешь кубки. Приоритеты.",
    ),
    RoflDeck(
        "one-brain-cell",
        "Один нейрон",
        (
            "Skeletons",
            "Bats",
            "Ice Spirit",
            "Fire Spirit",
            "Electro Spirit",
            "Heal Spirit",
            "Goblins",
            "Spear Goblins",
        ),
        "Один нейрон на восьмерых. Он уже сдался.",
    ),
    RoflDeck(
        "skull-emoji",
        "💀 колода",
        (
            "Skeletons",
            "Skeleton Army",
            "Skeleton Barrel",
            "Skeleton Dragons",
            "Giant Skeleton",
            "Graveyard",
            "Tombstone",
            "Guards",
        ),
        "💀💀💀. Не смешно? Значит, ты старпер.",
    ),
    RoflDeck(
        "cope-castle",
        "Замок отмазок",
        (
            "Elixir Collector",
            "Mirror",
            "Clone",
            "Heal Spirit",
            "Battle Healer",
            "Furnace",
            "Tombstone",
            "Barbarian Hut",
        ),
        "Копим отмазки у своей башни. Мете плевать.",
    ),
]

_CHAOS_TAGLINES = (
    "Алгоритм не виноват. Ты сам нажал «Заново».",
    "Это не баг — это рофл.",
    "Для смеха — пять звёзд. Для рейтинга — ноль.",
    "Сгенерировано на чистом угаре.",
    "Мета-аналитики ненавидят этот трюк.",
)

_CHAOS_NAMES = (
    "Хаос-черновик",
    "Случайный бред",
    "Алгоритм сказал «нет»",
    "Сертифицированный угар",
)


def pick_chaos_flavor() -> tuple[str, str]:
    return random.choice(_CHAOS_NAMES), random.choice(_CHAOS_TAGLINES)
