"""Meme / rofl deck presets — post-ironic chaos, not boomer puns."""

from __future__ import annotations

import random
from dataclasses import dataclass


@dataclass(frozen=True)
class RoflDeck:
    key: str
    name: str
    cards: tuple[str, ...]
    tagline: str


ROFL_DECKS: list[RoflDeck] = [
    RoflDeck(
        "skill-issue",
        "Skill Issue",
        (
            "Hog Rider",
            "Balloon",
            "Royal Giant",
            "Elite Barbarians",
            "Mega Knight",
            "Sparky",
            "X-Bow",
            "P.E.K.K.A",
        ),
        "Просто играй лучше. (Колода специально против этого.)",
    ),
    RoflDeck(
        "npc-pack",
        "NPC Starter Pack",
        (
            "Knight",
            "Archers",
            "Minions",
            "Arrows",
            "Fireball",
            "Giant",
            "Witch",
            "Baby Dragon",
        ),
        "Default settings игрок. Без DLC на мозги.",
    ),
    RoflDeck(
        "delulu",
        "Delulu Push",
        (
            "Balloon",
            "Rage",
            "Clone",
            "Freeze",
            "Wizard",
            "Witch",
            "Sparky",
            "Mirror",
        ),
        "Delulu is the solulu. Король всё равно упадёт (нет).",
    ),
    RoflDeck(
        "sigma-3am",
        "Sigma 3AM Grind",
        (
            "P.E.K.K.A",
            "Mega Knight",
            "Electro Giant",
            "Golem",
            "Giant",
            "Prince",
            "Dark Prince",
            "Lumberjack",
        ),
        "Проснулся. Заапгрейдил. Проиграл. Повтори. Sigma.",
    ),
    RoflDeck(
        "ohio-boss",
        "Ohio Final Boss",
        (
            "Mega Knight",
            "Electro Giant",
            "P.E.K.K.A",
            "Sparky",
            "Royal Giant",
            "Golem",
            "Lava Hound",
            "Wizard",
        ),
        "Only in Ohio. На самом деле — в каждом втором матче.",
    ),
    RoflDeck(
        "main-character",
        "Main Character",
        (
            "Golden Knight",
            "Princess",
            "Prince",
            "Dark Prince",
            "Wizard",
            "Witch",
            "Sparky",
            "Mega Knight",
        ),
        "Plot armor не включился. Сюжет — поражение.",
    ),
    RoflDeck(
        "low-taper",
        "Low Taper Fade",
        (
            "Royal Ghost",
            "Bandit",
            "Miner",
            "Goblin Drill",
            "Dart Goblin",
            "Skeleton Barrel",
            "Wall Breakers",
            "The Log",
        ),
        "What do you want bro? Low taper fade на мосту.",
    ),
    RoflDeck(
        "trust-me-bro",
        "Trust Me Bro",
        (
            "Elite Barbarians",
            "Rage",
            "Freeze",
            "Mirror",
            "Goblin Barrel",
            "Wall Breakers",
            "Skeleton Barrel",
            "Dart Goblin",
        ),
        "Trust me bro, это последний пуш. (Спойлер: не последний.)",
    ),
    RoflDeck(
        "chat-real",
        "Chat Is This Real",
        (
            "Mirror",
            "Clone",
            "Rage",
            "Freeze",
            "Tornado",
            "Zap",
            "The Log",
            "Giant Snowball",
        ),
        "Chat, is this winnable? No. Спасибо за attention.",
    ),
    RoflDeck(
        "tiktok-montage",
        "TikTok Montage",
        (
            "Sparky",
            "Inferno Dragon",
            "Balloon",
            "Freeze",
            "Rage",
            "Mirror",
            "Clone",
            "Mega Minion",
        ),
        "0.3 сек клипа, 8 эликсира и полный copium.",
    ),
    RoflDeck(
        "mom-bedtime",
        "Ещё один матч",
        (
            "Golem",
            "Lava Hound",
            "P.E.K.K.A",
            "Sparky",
            "Three Musketeers",
            "Electro Giant",
            "Giant",
            "Freeze",
        ),
        "Мама сказала спать. Ты сказал «ещё один». Классика.",
    ),
    RoflDeck(
        "l-plus-ratio",
        "L + Ratio",
        (
            "Rocket",
            "Fireball",
            "Lightning",
            "Poison",
            "Earthquake",
            "Arrows",
            "Zap",
            "The Log",
        ),
        "Войск нет. Зато L на короля закинуть можно.",
    ),
    RoflDeck(
        "fanum-tax",
        "Fanum Tax",
        (
            "Goblin Cage",
            "Elixir Collector",
            "Miner",
            "Goblin Drill",
            "Skeletons",
            "Ice Spirit",
            "Goblin Gang",
            "Fire Spirit",
        ),
        "Забираем эликсир. Отдаём трофеи. Fair trade.",
    ),
    RoflDeck(
        "gym-bro",
        "Gym Bro Cycle",
        (
            "Hog Rider",
            "Elite Barbarians",
            "Rage",
            "Prince",
            "P.E.K.K.A",
            "Giant",
            "Balloon",
            "Zap",
        ),
        "Leg day каждый раунд. Кардио — проигрыш.",
    ),
    RoflDeck(
        "grandma-hangup",
        "Бабушка положила трубку",
        (
            "Graveyard",
            "Mirror",
            "Clone",
            "Tornado",
            "Freeze",
            "Poison",
            "Bowler",
            "Ice Wizard",
        ),
        "Объяснял колоду бабушке. Она повесила трубку через 4 карты.",
    ),
    RoflDeck(
        "ping-999",
        "Ping 999",
        (
            "Golem",
            "Lava Hound",
            "Sparky",
            "Mega Knight",
            "Electro Giant",
            "P.E.K.K.A",
            "Giant",
            "Three Musketeers",
        ),
        "Лагает не интернет. Лагает решение играть это.",
    ),
    RoflDeck(
        "based-cringe",
        "Based & Cringe",
        (
            "Mirror",
            "Clone",
            "Rage",
            "Goblin Barrel",
            "Miner",
            "Wall Breakers",
            "Elite Barbarians",
            "Wizard",
        ),
        "Одновременно based и cringe. Schrödinger meta.",
    ),
    RoflDeck(
        "steal-brainrot",
        "Steal a Brainrot",
        (
            "Minion Horde",
            "Skeleton Army",
            "Goblin Gang",
            "Elite Barbarians",
            "Wizard",
            "Witch",
            "Fireball",
            "Rage",
        ),
        "Украл чужую колоду с TikTok. Вернул только минус trophies.",
    ),
    RoflDeck(
        "rizz-minus",
        "Rizz -100",
        (
            "Prince",
            "Dark Prince",
            "Knight",
            "Guards",
            "Valkyrie",
            "Mini P.E.K.K.A",
            "Barbarians",
            "Arrows",
        ),
        "Rizz отрицательный. Ratio положительный. У соперника.",
    ),
    RoflDeck(
        "touch-grass",
        "Touch Grass (нет)",
        (
            "Cannon",
            "Tesla",
            "Inferno Tower",
            "Tombstone",
            "Goblin Hut",
            "Barbarian Hut",
            "Goblin Cage",
            "X-Bow",
        ),
        "Сказали touch grass. Собрали только постройки у башни.",
    ),
    RoflDeck(
        "gen-alpha",
        "Gen Alpha National Team",
        (
            "Mega Knight",
            "Elite Barbarians",
            "Wizard",
            "Witch",
            "Sparky",
            "Freeze",
            "Rage",
            "Mirror",
        ),
        "Сборная поколения, которое смеётся над твоим лadder push.",
    ),
    RoflDeck(
        "aura-farm",
        "Aura Farming",
        (
            "Golden Knight",
            "Princess",
            "Sparky",
            "Freeze",
            "Mirror",
            "Wizard",
            "Balloon",
            "The Log",
        ),
        "Фармишь aura. Сливаешь trophies. Priorities.",
    ),
    RoflDeck(
        "one-brain-cell",
        "One Brain Cell",
        (
            "Skeletons",
            "Bats",
            "Ice Spirit",
            "Fire Spirit",
            "Electro Spirit",
            "Heal Spirit",
            "Goblins",
            "Spear Goblins",
        ),
        "Один нейрон на восьмерых. Он уже сдался.",
    ),
    RoflDeck(
        "skull-emoji",
        "💀 Deck",
        (
            "Skeletons",
            "Skeleton Army",
            "Skeleton Barrel",
            "Skeleton Dragons",
            "Giant Skeleton",
            "Graveyard",
            "Tombstone",
            "Guards",
        ),
        "💀💀💀. Не смешно? Значит ты old.",
    ),
    RoflDeck(
        "cope-castle",
        "Copium Castle",
        (
            "Elixir Collector",
            "Mirror",
            "Clone",
            "Heal Spirit",
            "Battle Healer",
            "Furnace",
            "Tombstone",
            "Barbarian Hut",
        ),
        "Копим copium у своей башни. Мета в шоке (ему плевать).",
    ),
]

_CHAOS_TAGLINES = (
    "Алгоритм не виноват. Ты нажал «Заново».",
    "Это не баг, это post-irony.",
    "School tier S+. Ladder tier F.",
    "Сгенерировано на чистом brainrot.",
    "Meta analysts hate this one trick.",
)

_CHAOS_NAMES = (
    "Chaos Draft",
    "Random Brainrot",
    "Algorithm Said No",
    "Certified Silly",
)


def pick_chaos_flavor() -> tuple[str, str]:
    return random.choice(_CHAOS_NAMES), random.choice(_CHAOS_TAGLINES)
